In [3]:

import os
import polars as pl 
from dotenv import load_dotenv
from datasets import load_dataset
from huggingface_hub import HfFileSystem

load_dotenv()

/Users/gsmith/Documents/Projects/Huggingface/hf-usa-spending/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

True

In [4]:
HF_TOKEN=os.getenv("HF_TOKEN")
HF_NAMESPACE=os.getenv("HF_NAMESPACE")
HF_BUCKET_NAME=os.getenv("HF_BUCKET_NAME")

In [5]:
!hf buckets list

ID                       PRIVATE       SIZE TOTAL_FILES CREATED_AT
------------------------ ------- ---------- ----------- ----------
ggsmith/usa-spending-raw         2734980740           8 2026-04-04

In [6]:
bucket_id = f"{HF_NAMESPACE}/{HF_BUCKET_NAME}"

fs = HfFileSystem()
# Get all parquet files in the bucket folder
files = fs.glob(f"hf://buckets/{bucket_id}/parquet/*.parquet")

# We open them individually because Polars scan_parquet doesn't 
# support a list of fsspec file objects directly as well as it does local paths.
# For EDA on multiple bucket files, it's often easiest to load them into a list:

# dfs = []
# for f_path in files[0]:
#     with fs.open(f"hf://{f_path}", mode="rb") as f:
#         dfs.append(pl.read_parquet(f))

# # Combine for analysis
# df = pl.concat(dfs)
# print(df.describe())

In [10]:
data = []
with fs.open(f"hf://{files[0]}", mode="rb") as f:
    data.append(pl.read_parquet(f))

In [18]:
data[0].select(
        [
            pl.col("award_id_piid").alias("Award ID"),
            pl.col("recipient_name").alias("Recipient Name"),
            pl.col("recipient_duns").alias("Recipient DUNS Number"),
            pl.col("period_of_performance_start_date").alias("Start Date"),
            pl.col("period_of_performance_current_end_date").alias("End Date"),
            pl.col("transaction_description").alias("Description"),
            pl.col("current_total_value_of_award").alias("Award Amount"),
            pl.col("awarding_agency_name").alias("Awarding Agency"),
            pl.col("awarding_sub_agency_name").alias("Awarding Sub Agency"),
            pl.col("award_type").alias("Contract Award Type"),
            pl.col("award_or_idv_flag").alias("Award Type"),
            pl.col("funding_agency_name").alias("Funding Agency"),
            pl.col("funding_sub_agency_name").alias("Funding Sub Agency"),
            pl.col("naics_code").alias("NAICS"),
            pl.col("product_or_service_code").alias("PSC"),
        ]
    )

shape: (1_000_000, 15)
┌─────────────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬────────┬──────┐
│ Award ID    ┆ Recipient  ┆ Recipient  ┆ Start Date ┆ … ┆ Funding    ┆ Funding    ┆ NAICS  ┆ PSC  │
│ ---         ┆ Name       ┆ DUNS       ┆ ---        ┆   ┆ Agency     ┆ Sub Agency ┆ ---    ┆ ---  │
│ str         ┆ ---        ┆ Number     ┆ date       ┆   ┆ ---        ┆ ---        ┆ str    ┆ str  │
│             ┆ str        ┆ ---        ┆            ┆   ┆ str        ┆ str        ┆        ┆      │
│             ┆            ┆ str        ┆            ┆   ┆            ┆            ┆        ┆      │
╞═════════════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════╪══════╡
│ W81XWH19C01 ┆ CHENEGA    ┆ null       ┆ 2019-07-11 ┆ … ┆ Department ┆ Defense    ┆ 561720 ┆ AN91 │
│ 37          ┆ HEALTHCARE ┆            ┆            ┆   ┆ of Defense ┆ Health     ┆        ┆      │
│             ┆ SERVICES   ┆            ┆            ┆   ┆            ┆ Agency     ┆        ┆      │
│             ┆ LL…        ┆            ┆            ┆   ┆            ┆            ┆        ┆      │
│ W90VN624PA0 ┆ SNB CO.,   ┆ null       ┆ 2024-09-18 ┆ … ┆ Department ┆ Department ┆ 339992 ┆ 5835 │
│ 23          ┆ LTD        ┆            ┆            ┆   ┆ of Defense ┆ of the Air ┆        ┆      │
│             ┆            ┆            ┆            ┆   ┆            ┆ Force      ┆        ┆      │
│ 1145PC23F04 ┆ MARTIN,    ┆ null       ┆ 2023-08-07 ┆ … ┆ Peace      ┆ Peace      ┆ 541930 ┆ R608 │
│ 87          ┆ CYNTHIA L  ┆            ┆            ┆   ┆ Corps      ┆ Corps      ┆        ┆      │
│ 1145PC24F03 ┆ MORE       ┆ null       ┆ 2024-11-01 ┆ … ┆ Peace      ┆ Peace      ┆ 339113 ┆ 6515 │
│ 53          ┆ PREPARED   ┆            ┆            ┆   ┆ Corps      ┆ Corps      ┆        ┆      │
│             ┆ LLC        ┆            ┆            ┆   ┆            ┆            ┆        ┆      │
│ 1131PL22FIQ ┆ WEBSTER    ┆ null       ┆ 2022-08-24 ┆ … ┆ United     ┆ United     ┆ 541611 ┆ R499 │
│ 11175       ┆ GROUP INC  ┆            ┆            ┆   ┆ States     ┆ States     ┆        ┆      │
│             ┆            ┆            ┆            ┆   ┆ Trade and  ┆ Trade and  ┆        ┆      │
│             ┆            ┆            ┆            ┆   ┆ Develo…    ┆ Develo…    ┆        ┆      │
│ …           ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …      ┆ …    │
│ 47QSCC24F41 ┆ W.W.       ┆ null       ┆ 2024-03-28 ┆ … ┆ General    ┆ Federal    ┆ 444110 ┆ 5340 │
│ GV          ┆ GRAINGER,  ┆            ┆            ┆   ┆ Services   ┆ Acquisitio ┆        ┆      │
│             ┆ INC.       ┆            ┆            ┆   ┆ Administra ┆ n Service  ┆        ┆      │
│             ┆            ┆            ┆            ┆   ┆ tio…       ┆            ┆        ┆      │
│ 47QSCC24F41 ┆ M-80       ┆ null       ┆ 2024-03-28 ┆ … ┆ General    ┆ Federal    ┆ 493190 ┆ R499 │
│ JM          ┆ SYSTEMS,   ┆            ┆            ┆   ┆ Services   ┆ Acquisitio ┆        ┆      │
│             ┆ INC.       ┆            ┆            ┆   ┆ Administra ┆ n Service  ┆        ┆      │
│             ┆            ┆            ┆            ┆   ┆ tio…       ┆            ┆        ┆      │
│ 47QSCC24F41 ┆ W.W.       ┆ null       ┆ 2024-03-29 ┆ … ┆ General    ┆ Federal    ┆ 444110 ┆ 5120 │
│ VB          ┆ GRAINGER,  ┆            ┆            ┆   ┆ Services   ┆ Acquisitio ┆        ┆      │
│             ┆ INC.       ┆            ┆            ┆   ┆ Administra ┆ n Service  ┆        ┆      │
│             ┆            ┆            ┆            ┆   ┆ tio…       ┆            ┆        ┆      │
│ 47QSCC24F42 ┆ W.W.       ┆ null       ┆ 2024-04-01 ┆ … ┆ General    ┆ Federal    ┆ 444110 ┆ 5120 │
│ Z6          ┆ GRAINGER,  ┆            ┆            ┆   ┆ Services   ┆ Acquisitio ┆        ┆      │
│             ┆ INC.       ┆            ┆            ┆   ┆ Administra ┆ n Service  ┆        ┆      │
│             ┆            ┆            ┆            ┆   ┆ tio…       ┆            ┆        ┆      │
│ 47QSCC24F44 ┆ LC         ┆ null       ┆ 2024-04-02 ┆ … ┆ General    ┆ Federal    ┆ 339940 ┆ 5120 │
│ 4S          ┆ INDUSTRIES ┆            ┆            ┆   ┆ Services   ┆ Acquisitio ┆        ┆      │
│             ┆ INC        ┆            ┆            ┆   ┆ Administra ┆ n Service  ┆        ┆      │
│             ┆            ┆            ┆            ┆   ┆ tio…       ┆            ┆        ┆      │
└─────────────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴────────┴──────┘

In [21]:
data[0].filter(pl.col("recipient_duns").is_not_null()).select("recipient_duns")

shape: (0, 1)
┌────────────────┐
│ recipient_duns │
│ ---            │
│ str            │
╞════════════════╡
└────────────────┘